# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import spgateway.models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0014_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='SpgatewaySlug',
            field=models.SlugField(default=spgateway.models.generate_slug, max_length=20, unique=True),
        ),
    ]
